### ISSUE TITLE
'webkitURL' is deprecated

### ISSUE THREAD

**Issue by vanoorschot** [Q42/TrelloScrum#104]
I've got this message in my Dev tools:

> 'webkitURL' is deprecated. Please use 'URL' instead.

on this rule: `window.URL = window.webkitURL || window.URL;`

**Comment by ArtursO** [comment]
I got the same issue. Not sure if it's impacting anything however.

**Comment by SeanColombo** [comment]
Thanks for the Issue!  Sorry I didn't stumble onto it until now. Seems like I've fixed it in the recent commit... it won't get picked up until the next time we do a deployment though (and I probably won't poke the extension-owners to release it just over this).
