### ISSUE TITLE
Points not displaying on cards and columns

### ISSUE THREAD

**Issue by robef** [Q42/TrelloScrum#110]
Today it seems points are not displaying on cards or columns:

![mvp _ trello - google chrome 2017-06-28 11 40 15](https://user-images.githubusercontent.com/11313876/27633347-b23d30b8-5bf6-11e7-92eb-9c9fcb28a6ce.png)

I'm on Chrome Windows Version 58.0.3029.110 (64-bit)

Scrum for Trello version is 1.99

**Comment by martijn94** [comment]
Confirming this behaviour on Mac with Chrome Version 59.0.3071.115 (Official Build) (64-bit). Also the Firefox extension seems to be broken. Most likely some changes on Trello's side.

**Comment by SeanColombo** [comment]
Can confirm that this also stopped working for me today as well (and got a similar report from a user).

It might be Trello changes, but another thing to keep in mind is that Chrome 59 has just been rolling out and is a fairly big change.  Will try to look into this late tonight if nobody has figured it out by then.

**Comment by vmueller71** [comment]
Same problem here, but still on Chrome 58.0.3029.110 on MacOS 10.12.5

**Comment by DataAutomation** [comment]
Same here. Windows... Version 58.0.3029.110 (64-bit)

**Comment by ArtursO** [comment]
Have the same issue here. On Chrome Version 59.0.3071.115 (Official Build) (64-bit). MacOS 10.12.5,

![image](https://user-images.githubusercontent.com/6081495/27651274-bcf6890a-5c05-11e7-9b03-d9fe0edc7546.png)

**Comment by greggackle** [comment]
Same problem here - and I have a presentation to give tomorrow on it!  Any idea how to fix?

**Comment by felzan** [comment]
+1

**Comment by spruke** [comment]
+1, this broke today for me in 58.0.3029.110 and OSX. 10.12.5 (16F73)

Same as everybody else is describing. Abruptly today the numbers stopped condensing into little labels and columns stopped summing.

**Comment by ulymarins** [comment]
+1, Ubuntu 16.04, Chrome Version 55.0.2883.87 (64-bit).

**Comment by Datahider** [comment]
I think it was a trello.com change 'cause same problem is on Mozilla FF 54.0 (32-bit) and Chrome 59.0.3071.115

**Comment by SeanColombo** [comment]
Figured it out. Got a fix coming...

**Comment by SeanColombo** [comment]
@greggackle I've asked the owners to do a release... if you have to do your presentation before that, there's only one character that needs to be changed.  Here's how you can fix it.

- Find [where the Chrome extensions are](https://stackoverflow.com/a/14544700/684852) on your computer.
- In the Scrum for Trello extension, open up `trelloScrum.js`
- Go to [line 620](https://github.com/Q42/TrelloScrum/blob/a0b8ed2acb3ffa063122bc6e580aaa7f7e9a5a6c/trelloscrum.js#L620) and delete the "a" from "'a.list-card-title'" so that it's just "'a.list-card-title'".
- Go to about://extensions in your browser's location bar which will take you to a list of extensions
- Click "reload" on Scrum for Trello

You should be good to go.

**Comment by SeanColombo** [comment]
Also, big thanks to @gjdycus for jumping on this and figuring out the problem. I blindly attacked it without realizing he'd already made a PR for it. 🤦‍♂️   Additional thanks to @bakorer for pointing out a more future-proof fix.

**Comment by SeanColombo** [comment]
v 1.99.2 has been submitted to Firefox for review.

**Comment by jkaizer** [comment]
The fixed version is pushed to the Chrome web store.
Thanks all!

**Comment by ArtursO** [comment]
@jkaizer @SeanColombo thanks for the awesome turn around on fixing this issue!!!!

**Comment by bakorer** [comment]
thx a lot :)

**Comment by SeanColombo** [comment]
The Firefox version has been approved and just now I uploaded a Safari version as well. You can wait for the automatic update or get the latest versions from http://scrumfortrello.com/
