### ISSUE TITLE
TrelloScrum is not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by jery-v** [Q42/TrelloScrum#115]
TrelloScrum is not compatible with Firefox Quantum

**Comment by cadesalaberry** [comment]
I would love to see an update as well 👍

**Comment by Patribu** [comment]
+1

**Comment by watsonalexander** [comment]
Hi,

would be great to update the scoring plugin for trello!!! Thanks!

**Comment by cadesalaberry** [comment]
I found a temporary solution using https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by SeanColombo** [comment]
I've submitted a version 1.101 to Mozilla Add-ons which will make it a WebExtension that's compatible with Quantum (FF 57+).

**Comment by SeanColombo** [comment]
I guess this is a duplicate of #113 so I'm going to close this one and follow-up there as the extension hopefully gets approved/released.
