### ISSUE TITLE
high CPU usage on Max OSX (with extension edit with emacs)

### ISSUE THREAD

**Issue by flamingbear** [Q42/TrelloScrum#27]
Hi guys, I'm leaving a note here and I will with the edit with emacs people too.  But since I see the effects of a problem in your software maybe you'll look into it?

The basic problem is 100%+ CPU usage on trello pages when both TrelloScrum and edit with emacs extensions are enabled.  I don't know if any other extensions cause this problem but I reproduced it by turning off extensions one at a time until I found one that when TrelloScrum is enabled, the cpu of a Google Chrome Renderer goes up to 100% and stays there until trello is closed, trelloScrum is disabled or edit with emacs is disabled.

Edit with Emacs 1.11
Trello Scrum 1.31

Cheers,
Matt

**Comment by donSchoe** [comment]
Having the same issue (100% cpu usage). But I don't use emacs extension. Only Scrum for Trello.
