### ISSUE TITLE
 Display of Scrum for Trello Points on cards disappears after an undetermined amount of time and for a seemingly unknown reason.  This can confuse people sometimes.

### ISSUE THREAD

**Issue by jasonsmithlumapictures** [Q42/TrelloScrum#51]
System: MacOSX
Chrome: v25.0.1364.160

Display of Scrum for Trello Points disappears on cards after an undetermined amount of time and for a seemingly unknown reason.  This can confuse people sometimes.

**Comment by SeanColombo** [comment]
Pretty sure this was fixed a couple of years ago :) it was really annoying for a while, but has been behaving for quite some time.  Please re-open if anyone sees something like this!
