### ISSUE TITLE
Incorrect Position of Modal boxes when Burndown for Trello is enabled

### ISSUE THREAD

**Issue by mmhan** [Q42/TrelloScrum#73]
When I have enabled Burndown for Trello the modal boxes tend to stick to the right side, 
![screen shot 2014-07-23 at 12 59 12 am](https://cloud.githubusercontent.com/assets/301672/3662927/af36702a-11ce-11e4-9f42-08b32e0edf5c.png)

Without Burndown for Trello
![screen shot 2014-07-23 at 12 58 40 am](https://cloud.githubusercontent.com/assets/301672/3662934/bd285216-11ce-11e4-8978-86fb70f57d78.png)

Is it just me or is it a valid issue?

**Comment by SeanColombo** [comment]
This was fixed with a subsequent push and has been fine for a while now. Closing as resolved :)
