### ISSUE TITLE
Estimates sum op to (NaN) when selecting (?) in a Checklist

### ISSUE THREAD

**Issue by JeroenBoersma** [Q42/TrelloScrum#82]
When using estimates in checklists and select (?) it will set (NaN) as title for the card.
Editing to a number will change in to (1) (NaN)

**Comment by SeanColombo** [comment]
I think this refers to this PR: https://github.com/Q42/TrelloScrum/pull/79

**Comment by JeroenBoersma** [comment]
PR is ready, closing my old request
