### ISSUE TITLE
Bug: Card #'s being shown in title

### ISSUE THREAD

**Issue by SimonEast** [Q42/TrelloScrum#88]
As mentioned in the [Chrome Store Support Forum](https://chrome.google.com/webstore/detail/scrum-for-trello/jdbcdblgjdpmfninkoogcfpnkjmndgje/support?utm_source=chrome-app-launcher-info-dialog), the card ###'s are being shown in the card titles.  Appears to have only started in the last day or so.

Let me know if you need screenshots or other debugging info.

**Comment by rickpastoor** [comment]
I think this is solved in https://github.com/Q42/TrelloScrum/commit/9bd5d0a34e2538a6f64a78b506676f7d13138f3d, but it is not live on the Chrome Webstore yet. Does anyone have an idea on when this will happen?

**Comment by mac-cain13** [comment]
As @rickpastoor says; that commit should fix it. We need @jkaizer to release to the store, will ask him to do that asap! :)

**Comment by johnlucas** [comment]
Yes please!

**Comment by jkaizer** [comment]
Sorry for the delay. It is pushed!

**Comment by mpareja** [comment]
Woot!

**Comment by johnlucas** [comment]
Awesome Jasper thanks! It's fixed on my browser.
