### ISSUE TITLE
Points not displaying

### ISSUE THREAD

**Issue by cadrell0** [Q42/TrelloScrum#95]
I need to edit the card and change the points to a different value, then change it back for it to be counted. Only edited cards show in the List / Board total.

Editing either the Estimated points or the consumed points seems to make both work for that card.

**Comment by cadrell0** [comment]
I see that the current version is 1.97, but the Chrome web store has 1.94.

**Comment by jeroenheijmans** [comment]
I can confirm this issue, also for the Firefox add-on version 1.96.1.

If I inspect in Chrome I do see the `badge` appear in the DOM, just with no points content:

``` HTML
<div class="badge badge-points point-count" 
      style="background-image: url(chrome-extension://jdbcdblgjdpmfninkoogcfpnkjmndgje/images/storypoints-icon.png)" 
      title="This card has  storypoints.">
</div>
```

If I "hack" the `div` and give it a number content things show up correctly in the browser.

**Comment by cadrell0** [comment]
Looks like it is working today. Chrome shows version 1.97 now
