### ISSUE TITLE
scrum for trello doesn't work with new Trello.com ui

### ISSUE THREAD

**Issue by shayhz** [Q42/TrelloScrum#96]
It seems that trello were updating their UI, so now clicking on a card subject doesn't show the estimated/consumed points.

**Comment by HarveyWilliams** [comment]
I clicked on the Scrum for Trello button which is by the "Team Visible" button on my board, and suddenly the extension was working again. Using version 1.98.2.

**Comment by sprihodko** [comment]
Just use version >= 1.98

**Comment by pedro380085** [comment]
Bug is still persistent for me.

**Comment by shayhz** [comment]
It click on the title and it takes it a lot of time to load (even if there are not too many cards).
Trello change with the title really screwed this plugin :(

**Comment by alepore** [comment]
Also need some other graphic fixes:

<img width="278" alt="screen shot 2016-06-02 at 08 00 13" src="https://cloud.githubusercontent.com/assets/557414/15735333/30941b68-2898-11e6-81f2-4c3f209af6d1.png">

**Comment by SeanColombo** [comment]
Pretty sure this is really old and no-longer relative. We did a panic'ed update after a Trello change a while back, and I think this was that one.
